name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Docker Action
      uses: zenato/docker-action@v1.0.0
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_key }}
        repository: rcwowbagger/raspberry
        tag: latest
      
