name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file Dockerfile.debian-arm32 --tag raspberrysensor:latest .
    - uses: actions/checkout@v2
    - name: Tag the Docker image
      run: docker tag raspberrysensor rcwowbagger/raspberrysensor
    - uses: actions/checkout@v2
    - name: Login to Docker
      run: docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_key }}
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: docker push rcwowbagger/raspberrysensor
